/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'emoji' : IDL.Text,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'customerPhone' : IDL.Text,
  'createdAt' : Time,
  'totalAmount' : IDL.Text,
  'customerId' : IDL.Principal,
  'items' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'mrp' : IDL.Opt(IDL.Text),
  'categoryId' : IDL.Text,
  'isPacked' : IDL.Bool,
  'name' : IDL.Text,
  'size' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'brand' : IDL.Opt(IDL.Text),
  'price' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLoyaltyPoints' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([Category], [], []),
  'createOrder' : IDL.Func([Order], [], []),
  'createProduct' : IDL.Func([Product], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
  'getLoyaltyPoints' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSeedData' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func([Category], [], []),
  'updateOrder' : IDL.Func([Order], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'emoji' : IDL.Text,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'customerPhone' : IDL.Text,
    'createdAt' : Time,
    'totalAmount' : IDL.Text,
    'customerId' : IDL.Principal,
    'items' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'mrp' : IDL.Opt(IDL.Text),
    'categoryId' : IDL.Text,
    'isPacked' : IDL.Bool,
    'name' : IDL.Text,
    'size' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'brand' : IDL.Opt(IDL.Text),
    'price' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLoyaltyPoints' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([Category], [], []),
    'createOrder' : IDL.Func([Order], [], []),
    'createProduct' : IDL.Func([Product], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
    'getLoyaltyPoints' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSeedData' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func([Category], [], []),
    'updateOrder' : IDL.Func([Order], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };