/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : string, 'name' : string, 'emoji' : string }
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'deliveryAddress' : string,
  'customerPhone' : string,
  'createdAt' : Time,
  'totalAmount' : string,
  'customerId' : Principal,
  'items' : string,
}
export interface Product {
  'id' : string,
  'mrp' : [] | [string],
  'categoryId' : string,
  'isPacked' : boolean,
  'name' : string,
  'size' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'brand' : [] | [string],
  'price' : string,
}
export type Time = bigint;
export interface UserProfile {
  'city' : string,
  'fullName' : string,
  'email' : string,
  'state' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLoyaltyPoints' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[Category], undefined>,
  'createOrder' : ActorMethod<[Order], undefined>,
  'createProduct' : ActorMethod<[Product], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[string], Category>,
  'getLoyaltyPoints' : ActorMethod<[Principal], bigint>,
  'getOrder' : ActorMethod<[string], Order>,
  'getProduct' : ActorMethod<[string], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSeedData' : ActorMethod<[], undefined>,
  'isAdmin' : ActorMethod<[string, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<[Category], undefined>,
  'updateOrder' : ActorMethod<[Order], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];